"use client";

import { useEffect,useState } from "react";
import { usePathname } from "next/navigation";
import { isPublicAccountPath } from "../../lib/auth/session-safety.js";

const CANONICAL_CORE_PATHS=new Set(["/","/login","/auth","/create"]);

export default function CreatorEncouragement(){
  const pathname=usePathname();
  const hidden=CANONICAL_CORE_PATHS.has(String(pathname||"/").split("?")[0]);
  const[status,setStatus]=useState(null);const[open,setOpen]=useState(false);const[reason,setReason]=useState("");const[code,setCode]=useState("");const[busy,setBusy]=useState(false);const[message,setMessage]=useState("");const[error,setError]=useState("");
  async function load(){if(hidden||isPublicAccountPath(pathname))return;try{const r=await fetch("/api/creator-support",{cache:"no-store",credentials:"same-origin"});if(!r.ok){if(r.status===401)return;throw new Error("Unable to load Creator Support.")}const d=await r.json();setStatus(d);if(d?.verifyCode&&!code)setCode(d.verifyCode)}catch{}}
  useEffect(()=>{if(hidden){setOpen(false);return}if(!isPublicAccountPath(pathname))void load()},[pathname,hidden]);
  useEffect(()=>{const body=document.body;if(open&&!hidden)body.dataset.liuiCreatorOpen="true";else delete body.dataset.liuiCreatorOpen;window.dispatchEvent(new CustomEvent("laneriq:creator-support-state",{detail:{open:Boolean(open&&!hidden)}}));return()=>{delete body.dataset.liuiCreatorOpen}},[open,hidden]);
  async function act(payload){setBusy(true);setError("");setMessage("");try{const r=await fetch("/api/creator-support",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)});const d=await r.json();if(!r.ok)throw new Error(d.error||"Unable to continue.");if(payload.action==="request")setMessage(d.status==="approved"?"Creator Support approved. Your one-time Verify Code is ready below.":"Request received. Admin will review it.");else setMessage("Creator Support activated. All currently available LANERIQ AI functions are unlocked for 3 months.");await load()}catch(e){setError(e.message||"Unable to continue.")}finally{setBusy(false)}}
  if(hidden||(!status?.showButton&&!status?.active&&!status?.request))return null;
  const pending=status?.request?.status==="pending";const approved=status?.request?.status==="approved";const canRequest=status?.eligible===true;
  return <aside className={`creatorEncourage ${open?"open":""}`} aria-label="Creator Encouragement Program">
    <button className="creatorSpark" onClick={()=>setOpen(v=>!v)} aria-expanded={open}><span>✨ Encourage Creator</span><small>个人 Creator 项目还没完成？可申请额外 3 个月全部功能使用期。</small></button>
    {open&&<div className="creatorPanel">
      <div className="creatorHead"><div><b>Creator Support Access</b><small>Individual Creator only · 3 months · all currently available LANERIQ AI functions</small></div><button onClick={()=>setOpen(false)} aria-label="Close">×</button></div>
      {status?.active?<div className="creatorSuccess"><b>Support active ✓</b><span>Valid until {status.validUntil?new Date(status.validUntil).toLocaleDateString():"—"}</span><small>When it expires, you may apply again if your personal project is still unfinished.</small></div>:<>
        {canRequest&&<div className="creatorApply"><p>LANERIQ AI wants individual Creators to finish what they started. Tell us briefly why you need more time.</p><textarea value={reason} onChange={e=>setReason(e.target.value)} maxLength={800} placeholder="My project is still unfinished because…"/><label><input type="checkbox" id="creatorIndividual"/> I confirm this is my individual Creator account, not a company/team account.</label><button disabled={busy} onClick={()=>{const checked=document.getElementById("creatorIndividual")?.checked===true;if(!checked){setError("Please confirm this is an individual Creator account.");return}void act({action:"request",reason,individualAttested:true})}}>{busy?"Sending…":"Request 3-Month Support"}</button></div>}
        {pending&&<div className="creatorPending"><b>Request pending</b><span>Approval mode: {status.request.approvalMode||"manual"}</span><small>You do not need to submit another request.</small></div>}
        {(approved||status?.verifyCode)&&<div className="creatorRedeem"><b>Enter Creator Support Verify Code</b><small>One-time, account-bound, non-transferable.</small><div><input value={code} onChange={e=>setCode(e.target.value.toUpperCase())} placeholder="CREATOR-XXXXXXXXXXXX" autoCapitalize="characters"/><button disabled={busy||!code.trim()} onClick={()=>void act({action:"redeem",code})}>{busy?"Activating…":"Activate 3 Months"}</button></div></div>}
      </>}
      {message&&<p className="creatorMsg">{message}</p>}{error&&<p className="creatorErr" role="alert">{error}</p>}
    </div>}
    <style jsx>{`.creatorEncourage{position:fixed;right:18px;bottom:92px;z-index:82;width:min(380px,calc(100vw - 28px));font-family:system-ui,-apple-system,sans-serif}.creatorSpark{width:100%;text-align:left;border:1px solid #ead06a66;border-radius:18px;padding:12px 14px;background:linear-gradient(135deg,#171329ee,#09241eee);box-shadow:0 16px 50px #0007;color:#fff;backdrop-filter:blur(18px)}.creatorSpark span{display:block;color:#f1d56b;font-weight:900;font-size:14px}.creatorSpark small{display:block;margin-top:4px;color:#c8d2cc;font-size:10px;line-height:1.45}.creatorPanel{margin-top:8px;border:1px solid #ffffff20;border-radius:20px;padding:15px;background:linear-gradient(155deg,#0b1717f5,#151027f3);color:#fff;box-shadow:0 24px 70px #0009;backdrop-filter:blur(22px)}.creatorHead{display:flex;justify-content:space-between;gap:12px}.creatorHead b,.creatorHead small{display:block}.creatorHead b{color:#f2d66f}.creatorHead small{margin-top:4px;color:#aebdb6;font-size:10px;line-height:1.4}.creatorHead button{border:0;background:transparent;color:#fff;font-size:24px}.creatorApply p{color:#c4cec9;font-size:12px;line-height:1.55}.creatorApply textarea{width:100%;min-height:84px;border-radius:12px;border:1px solid #ffffff20;background:#f5f1e8;color:#172019;padding:11px;resize:vertical}.creatorApply label{display:flex;gap:8px;margin:10px 0;color:#c8d2cc;font-size:11px;line-height:1.45}.creatorApply button,.creatorRedeem button{border:0;border-radius:12px;padding:10px 12px;background:linear-gradient(135deg,#f0d46c,#c59a35);color:#17120a;font-weight:900}.creatorPending,.creatorSuccess{display:grid;gap:5px;margin-top:14px;padding:12px;border:1px solid #ffffff16;border-radius:14px;background:#ffffff08}.creatorPending b{color:#f0d46c}.creatorSuccess b{color:#72e4a9}.creatorPending span,.creatorSuccess span{font-size:12px}.creatorPending small,.creatorSuccess small{color:#9eaea6;font-size:10px}.creatorRedeem{margin-top:14px}.creatorRedeem b,.creatorRedeem small{display:block}.creatorRedeem small{color:#9eaea6;font-size:10px;margin:4px 0 8px}.creatorRedeem>div{display:flex;gap:7px}.creatorRedeem input{min-width:0;flex:1;border-radius:11px;border:1px solid #ffffff22;background:#f5f1e8;color:#172019;padding:10px}.creatorMsg,.creatorErr{font-size:11px;line-height:1.45}.creatorMsg{color:#80e6b0}.creatorErr{color:#ffaaa0}@media(max-width:640px){.creatorEncourage{right:14px;bottom:88px}.creatorSpark{padding:11px 12px}.creatorRedeem>div{display:grid}}`}</style>
  </aside>;
}
