import {NextResponse} from "next/server";
import {POST as createStoryboard} from "../../video/storyboard/route.js";
import {openSuperGameDataSession,accountVerified} from "../../../../lib/game/super-game-data.js";
import {buildLivingWorldDemoPrompt} from "../../../../lib/game/living-world-demo-sync-v1.js";

const MAX=18*1024,UUID=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i,REQUEST=/^[A-Za-z0-9._:-]{1,160}$/;
function json(data,status=200){return NextResponse.json(data,{status,headers:{"Cache-Control":"private, no-store, max-age=0","Pragma":"no-cache","X-Content-Type-Options":"nosniff"}})}
function clean(v,max=500){return String(v||"").replace(/[\u0000-\u001f\u007f]/g," ").trim().slice(0,max)}

export async function POST(request){try{const length=Number(request.headers.get("content-length")||0);if(length>MAX)return json({success:false,error:"Demo request is too large."},413);const session=await openSuperGameDataSession();if(!session.user)return json({success:false,error:"Authentication required."},401);if(!accountVerified(session))return json({success:false,error:"Account verification is required."},403);const body=await request.json().catch(()=>null),projectId=clean(body?.projectId,80),requestId=clean(body?.requestId,160);if(!UUID.test(projectId))return json({success:false,error:"A valid Living World project is required."},400);if(!REQUEST.test(requestId))return json({success:false,error:"A stable demo request ID is required."},400);const project=await session.livingWorld.projectById(projectId);if(!project)return json({success:false,error:"Living World project not found."},404);const prompt=buildLivingWorldDemoPrompt({manifest:project.manifest,state:project.state,demoType:clean(body?.demoType,80)||"gameplay_demo",duration:Number(body?.duration)||30});const headers=new Headers(request.headers);headers.set("content-type","application/json");headers.delete("content-length");headers.set("x-laneriq-living-world-demo","v1");const forwarded=new Request(request.url,{method:"POST",headers,body:JSON.stringify({requestId,prompt,duration:Math.max(8,Math.min(120,Number(body?.duration)||30)),style:clean(body?.style,40)||"mixed",deviceClass:clean(body?.deviceClass,60)||"mobile"})});const response=await createStoryboard(forwarded);response.headers.set("X-LANERIQ-Living-World-Demo","v1");response.headers.set("Cache-Control","private, no-store, max-age=0");return response;}catch(error){console.error("LIVING_WORLD_DEMO_PLAN_ERROR",error?.code||error?.name||"unknown");return json({success:false,error:"Unable to plan this Living World demo right now."},500)}}
