import {NextResponse} from "next/server";
import {openSuperGameDataSession,accountVerified} from "../../../../lib/game/super-game-data.js";
import {normalizeLivingAvatarProfile,validateLivingAvatarConsent} from "../../../../lib/game/living-avatar-profile-v1.js";

const MAX=36*1024,REQUEST=/^[A-Za-z0-9._:-]{1,160}$/,UUID=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
function json(data,status=200){return NextResponse.json(data,{status,headers:{"Cache-Control":"private, no-store, max-age=0","Pragma":"no-cache","X-Content-Type-Options":"nosniff"}})}
function clean(v,max=1200){return String(v||"").replace(/[\u0000-\u001f\u007f]/g," ").replace(/\s+/g," ").trim().slice(0,max)}
function profileAssetIds(profile){return [...new Set([profile.avatarAssetId,profile.voice.assetId,...profile.appearance.outfitAssetIds,...profile.vehicles.assetIds,...profile.equipment.bindings.map(x=>x.assetId)].filter(Boolean))];}

export async function GET(){try{const session=await openSuperGameDataSession();if(!session.user)return json({success:false,error:"Authentication required."},401);const profiles=await session.avatarProfiles.list(50);return json({success:true,profiles,truth:"Living Avatar profiles are owner-scoped gameplay contracts. A profile does not claim a rendered 3D rig or voice clone."});}catch(error){console.error("LIVING_AVATAR_LIST_ERROR",error?.code||error?.name||"unknown");return json({success:false,error:"Unable to load Living Avatar profiles."},500)}}

export async function POST(request){try{const length=Number(request.headers.get("content-length")||0);if(length>MAX)return json({success:false,error:"Living Avatar request is too large."},413);const session=await openSuperGameDataSession();if(!session.user)return json({success:false,error:"Authentication required."},401);if(!accountVerified(session))return json({success:false,error:"Account verification is required."},403);const body=await request.json().catch(()=>null);if(!body||Buffer.byteLength(JSON.stringify(body),"utf8")>MAX)return json({success:false,error:"Invalid Living Avatar request."},400);const requestId=clean(body.requestId,160);if(!REQUEST.test(requestId))return json({success:false,error:"A stable Living Avatar request ID is required."},400);const existing=await session.avatarProfiles.byRequestId(requestId);if(existing)return json({success:true,replayed:true,profile:existing});const profile=normalizeLivingAvatarProfile(body.profile||body);if(!profile.avatarAssetId||!UUID.test(profile.avatarAssetId))return json({success:false,error:"Choose a private Avatar asset first."},400);const consent=validateLivingAvatarConsent(profile);if(!consent.ok)return json({success:false,error:consent.reason==="VOICE_CONSENT_REQUIRED"?"Explicit permission is required before a voice reference can be linked to a character.":"Explicit permission is required before a real-person likeness can become a Living Avatar."},403);const ids=profileAssetIds(profile),rows=await session.assets.byIds(ids);if(new Set(rows.map(x=>x.id)).size!==ids.length)return json({success:false,error:"One or more selected Living Avatar assets are unavailable or not owned by this account."},403);if(profile.voice.assetId){const voice=rows.find(x=>x.id===profile.voice.assetId);if(voice&&!String(voice.mime_type||"").startsWith("audio/")&&String(voice.category||"")!=="audio")return json({success:false,error:"The selected voice reference is not an audio asset."},400);}const saved=await session.avatarProfiles.insert({request_id:requestId,name:clean(profile.name,120)||"Living Avatar",avatar_asset_id:profile.avatarAssetId,profile,consent:{likenessMode:profile.likeness.mode,likenessConsent:profile.likeness.consentConfirmed,voiceConsent:profile.voice.consentConfirmed}});return json({success:true,replayed:false,profile:saved,truth:profile.truth},201);}catch(error){console.error("LIVING_AVATAR_CREATE_ERROR",error?.code||error?.name||"unknown");return json({success:false,error:"Unable to create this Living Avatar profile right now."},500)}}
