import {NextResponse} from "next/server";
import {createForgeBlueprintFromPrompt,normalizeForgeBlueprint,rebalanceForgeBlueprint,FORGE_CATEGORIES} from "../../../../../lib/game/game-intelligence-forge-v1.js";
import {openSuperGameDataSession,accountVerified} from "../../../../../lib/game/super-game-data.js";

const MAX=24*1024,REQUEST=/^[A-Za-z0-9._:-]{1,160}$/,UUID=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
function json(data,status=200){return NextResponse.json(data,{status,headers:{"Cache-Control":"private, no-store, max-age=0","Pragma":"no-cache","X-Content-Type-Options":"nosniff"}})}
function clean(v,max=2400){return String(v||"").replace(/[\u0000-\u001f\u007f]/g," ").trim().slice(0,max)}

export async function GET(){try{const session=await openSuperGameDataSession();if(!session.user)return json({success:false,error:"Authentication required."},401);const blueprints=await session.forge.list(100);return json({success:true,blueprints,categories:FORGE_CATEGORIES,truth:"Forge assets are owner-scoped structured game-design data. Prompt outputs are not rendered animation/VFX/audio assets."});}catch(error){console.error("GAME_FORGE_LIST_ERROR",error?.code||error?.name||"unknown");return json({success:false,error:"Unable to load Game Intelligence Forge assets."},500)}}
export async function POST(request){try{const len=Number(request.headers.get("content-length")||0);if(len>MAX)return json({success:false,error:"Forge request is too large."},413);const session=await openSuperGameDataSession();if(!session.user)return json({success:false,error:"Authentication required."},401);if(!accountVerified(session))return json({success:false,error:"Account verification is required."},403);const body=await request.json().catch(()=>null);if(!body||Buffer.byteLength(JSON.stringify(body),"utf8")>MAX)return json({success:false,error:"Invalid Forge request."},400);const requestId=clean(body.requestId,160);if(!REQUEST.test(requestId))return json({success:false,error:"A stable Forge request ID is required."},400);const prompt=clean(body.prompt,2400);if(!prompt)return json({success:false,error:"Describe the game power, weapon, item or combat design you want."},400);let blueprint=createForgeBlueprintFromPrompt(prompt,{category:body.category,element:body.element,name:body.name});if(clean(body.refineIntent,500))blueprint=rebalanceForgeBlueprint(blueprint,body.refineIntent);blueprint=normalizeForgeBlueprint(blueprint);const existing=await session.forge.byRequestId(requestId);if(existing){if(existing.prompt!==prompt||existing.category!==blueprint.category)return json({success:false,error:"This Forge request ID was already used for different inputs.",code:"FORGE_REQUEST_ID_CONFLICT"},409);return json({success:true,replayed:true,asset:existing});}const asset=await session.forge.insert({request_id:requestId,name:blueprint.name,category:blueprint.category,prompt,blueprint});return json({success:true,replayed:false,asset,truth:blueprint.truth},201);}catch(error){console.error("GAME_FORGE_CREATE_ERROR",error?.code||error?.name||"unknown");return json({success:false,error:"Unable to forge this game design right now."},500)}}
export async function DELETE(request){try{const session=await openSuperGameDataSession();if(!session.user)return json({success:false,error:"Authentication required."},401);const body=await request.json().catch(()=>null),id=clean(body?.id,80);if(!UUID.test(id))return json({success:false,error:"A valid Forge asset ID is required."},400);const data=await session.forge.remove(id);if(!data)return json({success:false,error:"Forge asset not found."},404);return json({success:true,deletedId:id});}catch(error){console.error("GAME_FORGE_DELETE_ERROR",error?.code||error?.name||"unknown");return json({success:false,error:"Unable to delete this Forge asset."},500)}}
