import {NextResponse} from "next/server";
import {createClient} from "../../../../../lib/supabase/server.js";
import {createForgeBlueprintFromPrompt,normalizeForgeBlueprint,rebalanceForgeBlueprint,FORGE_CATEGORIES} from "../../../../../lib/game/game-intelligence-forge-v1.js";

const MAX=24*1024,REQUEST=/^[A-Za-z0-9._:-]{1,160}$/,UUID=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
function json(data,status=200){return NextResponse.json(data,{status,headers:{"Cache-Control":"private, no-store, max-age=0","Pragma":"no-cache","X-Content-Type-Options":"nosniff"}})}
function clean(v,max=2400){return String(v||"").replace(/[\u0000-\u001f\u007f]/g," ").trim().slice(0,max)}
async function session(){const supabase=await createClient();const{data:{user},error}=await supabase.auth.getUser();return{supabase,user:error?null:user}}
const SELECT="id,request_id,name,category,prompt,blueprint,created_at,updated_at";
export async function GET(){const{supabase,user}=await session();if(!user)return json({success:false,error:"Authentication required."},401);const{data,error}=await supabase.from("game_forge_blueprints").select(SELECT).eq("user_id",user.id).order("created_at",{ascending:false}).limit(100);if(error)return json({success:false,error:"Unable to load Game Intelligence Forge assets."},500);return json({success:true,blueprints:data||[],categories:FORGE_CATEGORIES,truth:"Forge assets are owner-scoped structured game-design data. Prompt outputs are not rendered animation/VFX/audio assets."});}
export async function POST(request){try{const len=Number(request.headers.get("content-length")||0);if(len>MAX)return json({success:false,error:"Forge request is too large."},413);const{supabase,user}=await session();if(!user)return json({success:false,error:"Authentication required."},401);if(!user.confirmed_at&&!user.email_confirmed_at&&!user.phone_confirmed_at)return json({success:false,error:"Account verification is required."},403);const body=await request.json().catch(()=>null);if(!body||Buffer.byteLength(JSON.stringify(body),"utf8")>MAX)return json({success:false,error:"Invalid Forge request."},400);const requestId=clean(body.requestId,160);if(!REQUEST.test(requestId))return json({success:false,error:"A stable Forge request ID is required."},400);const prompt=clean(body.prompt,2400);if(!prompt)return json({success:false,error:"Describe the game power, weapon, item or combat design you want."},400);let blueprint=createForgeBlueprintFromPrompt(prompt,{category:body.category,element:body.element,name:body.name});if(clean(body.refineIntent,500))blueprint=rebalanceForgeBlueprint(blueprint,body.refineIntent);blueprint=normalizeForgeBlueprint(blueprint);const{data:existing,error:lookup}=await supabase.from("game_forge_blueprints").select(SELECT).eq("user_id",user.id).eq("request_id",requestId).maybeSingle();if(lookup)throw lookup;if(existing){if(existing.prompt!==prompt||existing.category!==blueprint.category)return json({success:false,error:"This Forge request ID was already used for different inputs.",code:"FORGE_REQUEST_ID_CONFLICT"},409);return json({success:true,replayed:true,asset:existing});}const{data,error}=await supabase.from("game_forge_blueprints").insert({user_id:user.id,request_id:requestId,name:blueprint.name,category:blueprint.category,prompt,blueprint}).select(SELECT).single();if(error)throw error;return json({success:true,replayed:false,asset:data,truth:blueprint.truth},201);}catch(error){console.error("GAME_FORGE_CREATE_ERROR",error?.code||error?.name||"unknown");return json({success:false,error:"Unable to forge this game design right now."},500)}}
export async function DELETE(request){const{supabase,user}=await session();if(!user)return json({success:false,error:"Authentication required."},401);const body=await request.json().catch(()=>null),id=clean(body?.id,80);if(!UUID.test(id))return json({success:false,error:"A valid Forge asset ID is required."},400);const{data,error}=await supabase.from("game_forge_blueprints").delete().eq("id",id).eq("user_id",user.id).select("id").maybeSingle();if(error)return json({success:false,error:"Unable to delete this Forge asset."},500);if(!data)return json({success:false,error:"Forge asset not found."},404);return json({success:true,deletedId:id});}
