-- LANERIQ Anti Scam Cloud Dead-Man storage contract.
-- No raw device id, URL, file name, message, contact or screen content is stored.
-- One current row per pseudonymous installation; no browsing/event history table.

create table if not exists public.anti_scam_guardian_leases (
  device_pseudonym text primary key check (device_pseudonym ~ '^[0-9a-f]{64}$'),
  lease_epoch bigint not null check (lease_epoch > 0),
  heartbeat_sequence bigint not null check (heartbeat_sequence > 0),
  lease_expires_at_ms bigint not null check (lease_expires_at_ms > 0),
  integrity_state text not null,
  emergency_level text not null,
  alert_delivery_state text not null,
  policy_version text not null,
  observed_at_ms bigint not null check (observed_at_ms > 0),
  received_at_ms bigint not null check (received_at_ms > 0),
  updated_at timestamptz not null default now()
);

alter table public.anti_scam_guardian_leases enable row level security;
revoke all on table public.anti_scam_guardian_leases from anon, authenticated;

create or replace function public.upsert_anti_scam_guardian_lease(
  p_device_pseudonym text,
  p_lease_epoch bigint,
  p_heartbeat_sequence bigint,
  p_lease_expires_at_ms bigint,
  p_integrity_state text,
  p_emergency_level text,
  p_alert_delivery_state text,
  p_policy_version text,
  p_observed_at_ms bigint,
  p_received_at_ms bigint
) returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
  current_row public.anti_scam_guardian_leases%rowtype;
  server_now_ms bigint := floor(extract(epoch from clock_timestamp()) * 1000)::bigint;
begin
  if p_device_pseudonym !~ '^[0-9a-f]{64}$'
     or p_lease_epoch <= 0
     or p_heartbeat_sequence <= 0
     or p_lease_expires_at_ms <= 0
     or p_observed_at_ms <= 0
     or p_received_at_ms <= 0 then
    return false;
  end if;

  -- received_at is server-generated by the trusted heartbeat handler. Refuse
  -- large clock divergence so a bad service caller cannot pin a row far ahead.
  if abs(p_received_at_ms - server_now_ms) > 120000 then return false; end if;
  if p_observed_at_ms - p_received_at_ms > 300000 then return false; end if;
  if p_lease_expires_at_ms <= p_observed_at_ms then return false; end if;
  if p_lease_expires_at_ms - p_observed_at_ms > 600000 then return false; end if;

  select * into current_row
  from public.anti_scam_guardian_leases
  where device_pseudonym = p_device_pseudonym
  for update;

  if found then
    if p_lease_epoch < current_row.lease_epoch then return false; end if;
    if p_lease_epoch = current_row.lease_epoch
       and p_heartbeat_sequence <= current_row.heartbeat_sequence then return false; end if;
    if p_received_at_ms <= current_row.received_at_ms then return false; end if;
    -- Durable per-install abuse bound. Normal clients are instructed to send at
    -- 60s cadence; a 15s minimum still tolerates retry/restart while limiting DB
    -- amplification by a compromised but still-attested installation.
    if p_received_at_ms - current_row.received_at_ms < 15000 then return false; end if;
  end if;

  insert into public.anti_scam_guardian_leases (
    device_pseudonym, lease_epoch, heartbeat_sequence, lease_expires_at_ms,
    integrity_state, emergency_level, alert_delivery_state, policy_version,
    observed_at_ms, received_at_ms, updated_at
  ) values (
    p_device_pseudonym, p_lease_epoch, p_heartbeat_sequence, p_lease_expires_at_ms,
    left(p_integrity_state, 64), left(p_emergency_level, 32), left(p_alert_delivery_state, 64), left(p_policy_version, 96),
    p_observed_at_ms, p_received_at_ms, now()
  )
  on conflict (device_pseudonym) do update set
    lease_epoch = excluded.lease_epoch,
    heartbeat_sequence = excluded.heartbeat_sequence,
    lease_expires_at_ms = excluded.lease_expires_at_ms,
    integrity_state = excluded.integrity_state,
    emergency_level = excluded.emergency_level,
    alert_delivery_state = excluded.alert_delivery_state,
    policy_version = excluded.policy_version,
    observed_at_ms = excluded.observed_at_ms,
    received_at_ms = excluded.received_at_ms,
    updated_at = now();

  return true;
end;
$$;

revoke all on function public.upsert_anti_scam_guardian_lease(text,bigint,bigint,bigint,text,text,text,text,bigint,bigint) from public, anon, authenticated;
grant execute on function public.upsert_anti_scam_guardian_lease(text,bigint,bigint,bigint,text,text,text,text,bigint,bigint) to service_role;

-- Service-only exact deletion. The public API must first authenticate and map an
-- authorized installation/account to its scoped pseudonym; clients never receive
-- service_role access.
create or replace function public.delete_anti_scam_guardian_lease(
  p_device_pseudonym text
) returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
  removed bigint := 0;
begin
  if p_device_pseudonym !~ '^[0-9a-f]{64}$' then return false; end if;
  delete from public.anti_scam_guardian_leases
  where device_pseudonym = p_device_pseudonym;
  get diagnostics removed = row_count;
  return removed > 0;
end;
$$;

revoke all on function public.delete_anti_scam_guardian_lease(text) from public, anon, authenticated;
grant execute on function public.delete_anti_scam_guardian_lease(text) to service_role;

-- Service-only retention purge. The function refuses cutoffs newer than 24h to
-- reduce accidental mass deletion; the application policy currently uses 30d.
create or replace function public.purge_anti_scam_guardian_leases(
  p_cutoff_received_at_ms bigint
) returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  removed bigint := 0;
  server_now_ms bigint := floor(extract(epoch from clock_timestamp()) * 1000)::bigint;
begin
  if p_cutoff_received_at_ms <= 0 then return -1; end if;
  if p_cutoff_received_at_ms > server_now_ms - 86400000 then return -1; end if;
  delete from public.anti_scam_guardian_leases
  where received_at_ms < p_cutoff_received_at_ms;
  get diagnostics removed = row_count;
  return removed;
end;
$$;

revoke all on function public.purge_anti_scam_guardian_leases(bigint) from public, anon, authenticated;
grant execute on function public.purge_anti_scam_guardian_leases(bigint) to service_role;

create index if not exists anti_scam_guardian_leases_observed_idx
  on public.anti_scam_guardian_leases (observed_at_ms desc);
create index if not exists anti_scam_guardian_leases_received_idx
  on public.anti_scam_guardian_leases (received_at_ms asc);
