import {NextResponse} from "next/server";
import {openSuperGameDataSession} from "../../../../lib/game/super-game-data.js";
import {playtestLivingWorld} from "../../../../lib/game/living-world-playtester-v1.js";
import {buildLivingWorldJsonExport,buildLivingWorldGdd,livingWorldExportCapabilities,LIVING_WORLD_EXPORT_TARGETS} from "../../../../lib/game/living-world-export-v1.js";

const MAX=12*1024,UUID=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
function json(data,status=200){return NextResponse.json(data,{status,headers:{"Cache-Control":"private, no-store, max-age=0","Pragma":"no-cache","X-Content-Type-Options":"nosniff"}})}
function fileName(value){return String(value||"LANERIQ-Living-World").replace(/[^A-Za-z0-9._-]+/g,"-").replace(/^-+|-+$/g,"").slice(0,80)||"LANERIQ-Living-World";}

export async function POST(request){try{const length=Number(request.headers.get("content-length")||0);if(length>MAX)return json({success:false,error:"Export request is too large."},413);const session=await openSuperGameDataSession();if(!session.user)return json({success:false,error:"Authentication required."},401);const body=await request.json().catch(()=>null),projectId=String(body?.projectId||""),format=String(body?.format||"json");if(!UUID.test(projectId))return json({success:false,error:"A valid Living World project is required."},400);if(!Object.hasOwn(LIVING_WORLD_EXPORT_TARGETS,format))return json({success:false,error:"Unknown Living World export target.",capabilities:livingWorldExportCapabilities()},400);if(!LIVING_WORLD_EXPORT_TARGETS[format].supported)return json({success:false,error:`${format} package export is not implemented yet.`,code:"EXPORT_TARGET_ROADMAP",capabilities:livingWorldExportCapabilities()},409);const project=await session.livingWorld.projectById(projectId);if(!project)return json({success:false,error:"Living World project not found."},404);const ids=Array.isArray(project.manifest?.forgeBlueprintIds)?project.manifest.forgeBlueprintIds:[],rows=ids.length?await session.forge.byIds(ids):[],byId=new Map(rows.map(x=>[x.id,x.blueprint])),forge=ids.map(id=>byId.get(id)).filter(Boolean);const report=playtestLivingWorld({manifest:project.manifest,state:project.state,forgeBlueprints:forge});const base=fileName(project.name);if(format==="gdd_markdown"){const bodyText=buildLivingWorldGdd(project.manifest,project.state,report);return new Response(bodyText,{status:200,headers:{"Content-Type":"text/markdown; charset=utf-8","Content-Disposition":`attachment; filename="${base}-GDD.md"`,`Cache-Control":"private, no-store, max-age=0","X-Content-Type-Options":"nosniff"}});}const bundle=buildLivingWorldJsonExport(project.manifest,project.state,report);return new Response(JSON.stringify(bundle,null,2),{status:200,headers:{"Content-Type":"application/json; charset=utf-8","Content-Disposition":`attachment; filename="${base}.living-world.json"`,`Cache-Control":"private, no-store, max-age=0","X-Content-Type-Options":"nosniff"}});}catch(error){console.error("LIVING_WORLD_EXPORT_ERROR",error?.code||error?.name||"unknown");return json({success:false,error:"Unable to export this Living World right now."},500)}}
