import {timingSafeEqual} from "node:crypto";
import {NextResponse} from "next/server";
import {createAvatarTrustedIssuerRegistry,registerAvatarTrustedIssuer} from "../../../../../lib/ai/avatar-trusted-issuer-registry-v1.js";
import {createAvatarEvidenceRegistry} from "../../../../../lib/ai/avatar-evidence-registry-v1.js";
import {evaluateAvatarEvidenceExecutionIntake} from "../../../../../lib/ai/avatar-evidence-execution-intake-v1.js";
import {appendAvatarReleaseEvidence} from "../../../../../lib/cloud/avatar-evidence-store.js";
export const runtime="nodejs";
const MAX_BYTES=48*1024;
function json(payload,status=200){return NextResponse.json(payload,{status,headers:{"Cache-Control":"private, no-store, max-age=0","Pragma":"no-cache","X-Content-Type-Options":"nosniff"}});}
function sameSecret(value,expected){const a=Buffer.from(String(value||"")),b=Buffer.from(String(expected||""));return a.length===b.length&&a.length>=24&&timingSafeEqual(a,b);}
function loadIssuerRegistry(){const raw=process.env.LANERIQ_AVATAR_TRUSTED_ISSUERS_JSON||"";if(!raw)return null;let defs;try{defs=JSON.parse(raw);}catch{return null;}if(!Array.isArray(defs)||!defs.length||defs.length>32)return null;let registry=createAvatarTrustedIssuerRegistry({registryId:"avatar-live-issuers-env"});try{for(const def of defs)registry=registerAvatarTrustedIssuer(registry,def);}catch{return null;}return registry;}
export async function POST(request){try{const expected=process.env.LANERIQ_AVATAR_EVIDENCE_INTAKE_TOKEN||"";if(!expected)return json({error:"Evidence intake is not configured.",code:"EVIDENCE_INTAKE_NOT_CONFIGURED"},503);const auth=request.headers.get("authorization")||"";const token=auth.startsWith("Bearer ")?auth.slice(7):"";if(!sameSecret(token,expected))return json({error:"Release-control authorization required.",code:"EVIDENCE_INTAKE_AUTH_REQUIRED"},401);const length=Number(request.headers.get("content-length")||0);if(length>MAX_BYTES)return json({error:"Evidence payload is too large."},413);const body=await request.json().catch(()=>null);if(!body||Buffer.byteLength(JSON.stringify(body),"utf8")>MAX_BYTES)return json({error:"Invalid evidence payload."},400);const issuers=loadIssuerRegistry();if(!issuers)return json({error:"Trusted issuer registry is not configured.",code:"TRUSTED_ISSUER_REGISTRY_NOT_CONFIGURED"},503);const evidenceRegistry=createAvatarEvidenceRegistry({registryId:`intake:${String(body?.envelope?.releaseId||"").slice(0,80)}`});const evaluation=evaluateAvatarEvidenceExecutionIntake({envelope:body.envelope,issuerRegistry:issuers,evidenceRegistry,expectedHeadSha:body.expectedHeadSha,nowMs:Date.now(),minimumTrust:"production"});if(!evaluation.pass)return json({success:false,code:"EVIDENCE_REJECTED",reasons:evaluation.reasons,quarantined:true},422);const persistentEnabled=process.env.LANERIQ_AVATAR_EVIDENCE_STORE_ENABLED==="1";let persisted=false;if(persistentEnabled){const a=body?.envelope?.attestation||{};const stored=await appendAvatarReleaseEvidence({releaseControlAuthorized:true,record:{evidenceDigest:a.evidenceDigest,releaseId:body.envelope.releaseId,headSha:evaluation.headSha,buildId:body.envelope.buildId,sourceType:evaluation.sourceType,capability:a.capability,issuerId:a.issuer,probeId:a.probeId,claims:a.claims,observedAtMs:a.observedAtMs,expiresAtMs:a.expiresAtMs}});if(!stored.ok)return json({success:false,code:"PERSISTENT_EVIDENCE_STORE_WRITE_FAILED",detail:stored.code,quarantined:true},503);persisted=true;}return json({success:true,contract:evaluation.contract,releaseId:evaluation.releaseId,headSha:evaluation.headSha,sourceType:evaluation.sourceType,evidenceDigest:evaluation.evidenceDigest,persistentRegistryWrite:persisted,requiresProductionEvidenceStore:!persisted});}catch{return json({error:"Unable to process Avatar evidence."},500);}}
