"use client";
import Link from "next/link";

export default function SceneAssetPicker({assets=[],selected=[],onChange}){
  const selectedSet=new Set(selected);
  function toggle(id){const next=selectedSet.has(id)?selected.filter(x=>x!==id):selected.length>=20?selected:[...selected,id];onChange?.(next);}
  return <article className="sceneAssets"><div className="head"><b>03</b><span><small>SCENE / MEDIA SOURCE</small><h2>Image Studio + Asset Library</h2></span><div className="links"><Link href="/image-studio?mode=create">+ Image</Link><Link href="/asset-library">Library</Link></div></div>
    {assets.length?<div className="grid">{assets.map(asset=><button type="button" key={asset.id} className={selectedSet.has(asset.id)?"on":""} onClick={()=>toggle(asset.id)}>
      <span className="preview">{asset.category==="image"?<img src={asset.url} alt={asset.name}/>:<span className="video">▶</span>}</span><b>{asset.name}</b><small>{asset.category} · private asset</small><em>{selectedSet.has(asset.id)?"✓ Selected":"Use in Game"}</em>
    </button>)}</div>:<div className="empty"><b>No reusable scene assets yet</b><span>Create an image/video or add one to Asset Library. This is optional.</span><div><Link href="/image-studio?mode=create">Create Image</Link><Link href="/asset-library">Open Asset Library</Link></div></div>}
    <p className="truth">Selected assets remain owner-scoped references. They can guide environment, props, UI and scene continuity; they are not published or shared across customers by this step.</p>
    <style jsx>{`.sceneAssets{padding:15px;min-width:0;border:1px solid #68ceff33;background:linear-gradient(155deg,#0a2148e8,#050e25f4);border-radius:22px;box-shadow:0 20px 65px #0008;backdrop-filter:blur(18px)}.head{display:grid;grid-template-columns:42px 1fr auto;gap:9px;align-items:center;margin-bottom:10px}.head>b{width:40px;height:40px;display:grid;place-items:center;border-radius:13px;background:#14376f;color:#79d8ff}.head small{color:#f1bd61;font-weight:900;letter-spacing:.13em;font-size:9px}.head h2{margin:3px 0;font-size:20px}.links{display:flex;gap:5px}.links a,.empty a{color:#79dbff;text-decoration:none;border:1px solid #65ccff44;border-radius:999px;padding:8px 9px;background:#081b3ddd;font-size:10px}.grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:7px;max-height:390px;overflow:auto}.grid>button{min-width:0;border:1px solid #ffffff13;border-radius:12px;background:#06142d;color:#fff;text-align:left;padding:6px}.grid>button.on{border-color:#efbd5c;background:#30240f}.preview{display:grid;place-items:center;width:100%;aspect-ratio:1.35;border-radius:8px;overflow:hidden;background:#071830}.preview img{width:100%;height:100%;object-fit:cover}.video{font-size:30px;color:#79dbff}.grid b,.grid small,.grid em{display:block;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.grid b{font-size:10px;margin:7px 3px 0}.grid small{color:#8fabca;font-size:8px;margin:3px}.grid em{font-style:normal;color:#73d9ff;font-size:9px;margin:5px 3px}.empty{min-height:180px;display:grid;place-items:center;align-content:center;text-align:center;gap:7px;color:#92aac3}.empty>div{display:flex;gap:6px}.truth{margin:9px 1px 0;color:#829bb5;font-size:9px;line-height:1.45}@media(max-width:640px){.head{grid-template-columns:42px 1fr}.head .links{grid-column:1/-1}.grid{grid-template-columns:repeat(2,minmax(0,1fr))}}`}</style>
  </article>;
}
